// <auto-generated />
using System;
using GO2.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GO2.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330172909_add_terrain_symbol_classes_and_catalog")]
    partial class add_terrain_symbol_classes_and_catalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GO2.Api.Models.DigitizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("IoU")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MacroF1")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapVersionId");

                    b.HasIndex("MapId", "OwnerUserId", "CreatedAtUtc");

                    b.ToTable("DigitizationJobs");
                });

            modelBuilder.Entity("GO2.Api.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("GO2.Api.Models.MapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapVersions");
                });

            modelBuilder.Entity("GO2.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GO2.Api.Models.TerrainObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeometryKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("TerrainClass")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TerrainObjectTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Traversability")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("MapVersionId");

                    b.HasIndex("TerrainObjectTypeId");

                    b.ToTable("TerrainObjects", t =>
                        {
                            t.HasCheckConstraint("CK_TerrainObject_Traversability_0_100", "\"Traversability\" >= 0 AND \"Traversability\" <= 100");
                        });
                });

            modelBuilder.Entity("GO2.Api.Models.TerrainObjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SymbolCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SymbolStyle")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TerrainClass")
                        .HasColumnType("integer");

                    b.Property<decimal>("Traversability")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SymbolCode")
                        .IsUnique()
                        .HasFilter("\"IsSystem\" = true AND \"SymbolCode\" <> ''");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "SymbolCode")
                        .IsUnique()
                        .HasFilter("\"SymbolCode\" <> ''");

                    b.ToTable("TerrainObjectTypes", t =>
                        {
                            t.HasCheckConstraint("CK_TerrainObjectType_Traversability_0_100", "\"Traversability\" >= 0 AND \"Traversability\" <= 100");
                        });
                });

            modelBuilder.Entity("GO2.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GO2.Api.Models.DigitizationJob", b =>
                {
                    b.HasOne("GO2.Api.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GO2.Api.Models.MapVersion", "MapVersion")
                        .WithMany()
                        .HasForeignKey("MapVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("MapVersion");
                });

            modelBuilder.Entity("GO2.Api.Models.Map", b =>
                {
                    b.HasOne("GO2.Api.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("GO2.Api.Models.MapVersion", b =>
                {
                    b.HasOne("GO2.Api.Models.Map", "Map")
                        .WithMany("Versions")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GO2.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("GO2.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GO2.Api.Models.TerrainObject", b =>
                {
                    b.HasOne("GO2.Api.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GO2.Api.Models.MapVersion", "MapVersion")
                        .WithMany("TerrainObjects")
                        .HasForeignKey("MapVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GO2.Api.Models.TerrainObjectType", "TerrainObjectType")
                        .WithMany()
                        .HasForeignKey("TerrainObjectTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Map");

                    b.Navigation("MapVersion");

                    b.Navigation("TerrainObjectType");
                });

            modelBuilder.Entity("GO2.Api.Models.Map", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GO2.Api.Models.MapVersion", b =>
                {
                    b.Navigation("TerrainObjects");
                });

            modelBuilder.Entity("GO2.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
