using GO2.Api.Models;

namespace GO2.Api.Services;

public sealed record TerrainSystemTypeSeed(
    TerrainClass TerrainClass,
    string SymbolCode,
    string SymbolStyle,
    string Name,
    string Color,
    string Icon,
    decimal Traversability,
    string Comment);

public static class TerrainSymbolCatalog
{
    public static IReadOnlyCollection<TerrainSystemTypeSeed> All { get; } =
    [
        // Рельеф (ISOM 100).
        new(TerrainClass.Relief, "101", "line", "Горизонталь", "#8B5A2B", "mountain", 55m, "Базовый рельеф"),
        new(TerrainClass.Relief, "102", "line", "Утолщенная горизонталь", "#8B5A2B", "mountain", 55m, "Базовый рельеф"),
        new(TerrainClass.Relief, "103", "line", "Вспомогательная горизонталь", "#8B5A2B", "mountain", 55m, "Базовый рельеф"),
        new(TerrainClass.Relief, "104", "line", "Земляной обрыв", "#8B5A2B", "triangle-alert", 20m, "Резкое изменение уровня"),
        new(TerrainClass.Relief, "105", "line", "Земляной вал/стенка", "#8B5A2B", "triangle-alert", 30m, "Ограничивает скорость"),
        new(TerrainClass.Relief, "106", "line", "Разрушенный земляной вал", "#8B5A2B", "triangle-alert", 45m, "Частично проходим"),
        new(TerrainClass.Relief, "107", "line", "Эрозионный овраг", "#8B5A2B", "waves", 35m, "Проходим с замедлением"),
        new(TerrainClass.Relief, "108", "line", "Малый овраг/сухая канава", "#8B5A2B", "waves", 45m, "Умеренное замедление"),
        new(TerrainClass.Relief, "109", "point", "Малый бугор", "#8B5A2B", "circle", 60m, "Локальная форма рельефа"),
        new(TerrainClass.Relief, "110", "point", "Вытянутый малый бугор", "#8B5A2B", "circle", 60m, "Локальная форма рельефа"),
        new(TerrainClass.Relief, "111", "point", "Малая впадина", "#8B5A2B", "circle", 55m, "Локальная форма рельефа"),
        new(TerrainClass.Relief, "112", "point", "Яма", "#8B5A2B", "circle", 25m, "Опасный участок"),
        new(TerrainClass.Relief, "113", "area", "Неровная поверхность", "#8B5A2B", "grid-2x2", 45m, "Снижение скорости"),
        new(TerrainClass.Relief, "114", "area", "Сильно неровная поверхность", "#8B5A2B", "grid-2x2", 30m, "Сильное снижение скорости"),
        new(TerrainClass.Relief, "115", "point", "Выраженная форма рельефа", "#8B5A2B", "landmark", 50m, "Ориентир"),

        // Скалы и камни (ISOM 200).
        new(TerrainClass.RocksAndStones, "201", "line", "Непреодолимая скала", "#6B7280", "mountain", 0m, "Непреодолимо"),
        new(TerrainClass.RocksAndStones, "202", "line", "Скала", "#6B7280", "mountain", 20m, "Сложнопроходимо"),
        new(TerrainClass.RocksAndStones, "203", "point", "Скалистая яма/пещера", "#6B7280", "cave", 10m, "Опасный участок"),
        new(TerrainClass.RocksAndStones, "204", "point", "Камень", "#6B7280", "circle", 50m, "Точечное препятствие"),
        new(TerrainClass.RocksAndStones, "205", "point", "Крупный камень", "#6B7280", "circle", 40m, "Точечное препятствие"),
        new(TerrainClass.RocksAndStones, "206", "area", "Глыба/скальный столб", "#6B7280", "pentagon", 20m, "Крупное препятствие"),
        new(TerrainClass.RocksAndStones, "207", "point", "Группа камней", "#6B7280", "circles-three", 35m, "Снижение скорости"),
        new(TerrainClass.RocksAndStones, "208", "area", "Каменистое поле", "#6B7280", "triangle", 35m, "Снижение скорости"),
        new(TerrainClass.RocksAndStones, "209", "area", "Плотное каменистое поле", "#6B7280", "triangle", 20m, "Сильное снижение скорости"),
        new(TerrainClass.RocksAndStones, "210", "area", "Каменистый грунт (медленный бег)", "#6B7280", "dot", 65m, "Скорость 60-80%"),
        new(TerrainClass.RocksAndStones, "211", "area", "Каменистый грунт (шаг)", "#6B7280", "dot", 40m, "Скорость 20-60%"),
        new(TerrainClass.RocksAndStones, "212", "area", "Каменистый грунт (продирание)", "#6B7280", "dot", 15m, "Скорость <20%"),
        new(TerrainClass.RocksAndStones, "213", "area", "Песчаный грунт", "#C0841A", "waves", 70m, "Умеренное замедление"),
        new(TerrainClass.RocksAndStones, "214", "area", "Голая скала", "#9CA3AF", "mountain", 75m, "Обычно проходимо"),
        new(TerrainClass.RocksAndStones, "215", "line", "Траншея", "#6B7280", "pickaxe", 30m, "Снижение скорости"),

        // Гидрография (ISOM 300).
        new(TerrainClass.Hydrography, "301", "area", "Непересекаемый водоем", "#2563EB", "waves", 0m, "Непреодолимо"),
        new(TerrainClass.Hydrography, "302", "area", "Мелкий водоем", "#3B82F6", "waves", 35m, "Пересекается с замедлением"),
        new(TerrainClass.Hydrography, "303", "point", "Водяная яма", "#3B82F6", "droplets", 30m, "Локальное препятствие"),
        new(TerrainClass.Hydrography, "304", "line", "Пересекаемый водоток", "#3B82F6", "waves", 45m, "Умеренное замедление"),
        new(TerrainClass.Hydrography, "305", "line", "Малый пересекаемый водоток", "#3B82F6", "waves", 55m, "Умеренное замедление"),
        new(TerrainClass.Hydrography, "306", "line", "Сезонный водоканал", "#60A5FA", "waves", 60m, "Часто проходим"),
        new(TerrainClass.Hydrography, "307", "area", "Непроходимое болото", "#1D4ED8", "pocket-knife", 0m, "Непреодолимо"),
        new(TerrainClass.Hydrography, "308", "area", "Болото", "#3B82F6", "pocket-knife", 30m, "Сильное замедление"),
        new(TerrainClass.Hydrography, "309", "line", "Узкое болото", "#60A5FA", "pocket-knife", 45m, "Умеренное замедление"),
        new(TerrainClass.Hydrography, "310", "area", "Неясное/сезонное болото", "#60A5FA", "pocket-knife", 40m, "Сильное замедление"),
        new(TerrainClass.Hydrography, "311", "point", "Колодец/резервуар", "#2563EB", "droplet", 70m, "Ориентир"),
        new(TerrainClass.Hydrography, "312", "point", "Родник", "#2563EB", "droplet", 75m, "Ориентир"),
        new(TerrainClass.Hydrography, "313", "point", "Выраженный водный объект", "#2563EB", "landmark", 70m, "Требует легенду"),

        // Растительность (ISOM 400).
        new(TerrainClass.Vegetation, "401", "area", "Открытая местность", "#FACC15", "sun", 90m, "Высокая скорость"),
        new(TerrainClass.Vegetation, "402", "area", "Открытая местность с редкими деревьями", "#EAB308", "trees", 85m, "Высокая скорость"),
        new(TerrainClass.Vegetation, "403", "area", "Грубая открытая местность", "#CA8A04", "grass", 70m, "Умеренное замедление"),
        new(TerrainClass.Vegetation, "404", "area", "Грубая открытая с редкими деревьями", "#CA8A04", "trees", 65m, "Умеренное замедление"),
        new(TerrainClass.Vegetation, "405", "area", "Лес", "#16A34A", "trees", 75m, "Базовая проходимость леса"),
        new(TerrainClass.Vegetation, "406", "area", "Растительность: медленный бег", "#22C55E", "trees", 70m, "Скорость 60-80%"),
        new(TerrainClass.Vegetation, "407", "area", "Растительность: медленно, хорошая видимость", "#22C55E", "tree-pine", 72m, "Скорость 60-80%"),
        new(TerrainClass.Vegetation, "408", "area", "Растительность: шаг", "#15803D", "trees", 45m, "Скорость 20-60%"),
        new(TerrainClass.Vegetation, "409", "area", "Растительность: шаг, хорошая видимость", "#15803D", "tree-pine", 50m, "Скорость 20-60%"),
        new(TerrainClass.Vegetation, "410", "area", "Растительность: продирание", "#166534", "trees", 15m, "Скорость <20%"),
        new(TerrainClass.Vegetation, "412", "area", "Культивируемая земля", "#EAB308", "wheat", 60m, "Сезонно изменяется"),
        new(TerrainClass.Vegetation, "413", "area", "Сад", "#EAB308", "apple", 55m, "Сезонно изменяется"),
        new(TerrainClass.Vegetation, "414", "area", "Виноградник", "#EAB308", "leaf", 50m, "Частично ограничивает бег"),
        new(TerrainClass.Vegetation, "415", "line", "Граница культивации", "#166534", "git-branch", 80m, "Линейная граница"),
        new(TerrainClass.Vegetation, "416", "line", "Граница растительности", "#166534", "git-branch", 78m, "Линейная граница"),
        new(TerrainClass.Vegetation, "417", "point", "Выраженное крупное дерево", "#16A34A", "tree-pine", 80m, "Ориентир"),
        new(TerrainClass.Vegetation, "418", "point", "Выраженный куст/дерево", "#16A34A", "tree-pine", 78m, "Ориентир"),
        new(TerrainClass.Vegetation, "419", "point", "Выраженная вегетационная деталь", "#16A34A", "leaf", 78m, "Ориентир"),

        // Искусственные объекты (ISOM 500).
        new(TerrainClass.ManMade, "501", "area", "Мощеная поверхность", "#374151", "square", 98m, "Очень быстро"),
        new(TerrainClass.ManMade, "502", "line", "Широкая дорога", "#111827", "route", 97m, "Очень быстро"),
        new(TerrainClass.ManMade, "503", "line", "Дорога", "#111827", "route", 95m, "Быстро"),
        new(TerrainClass.ManMade, "504", "line", "Колея", "#374151", "route", 90m, "Быстро"),
        new(TerrainClass.ManMade, "505", "line", "Тропа", "#374151", "footprints", 92m, "Быстро"),
        new(TerrainClass.ManMade, "506", "line", "Малая тропа", "#4B5563", "footprints", 88m, "Быстро"),
        new(TerrainClass.ManMade, "507", "line", "Слабо выраженная тропа", "#4B5563", "footprints", 80m, "Умеренно"),
        new(TerrainClass.ManMade, "508", "line", "Просека/линейный след", "#4B5563", "slash", 82m, "Умеренно"),
        new(TerrainClass.ManMade, "509", "line", "Железная дорога", "#111827", "train-track", 0m, "Запрещено/опасно"),
        new(TerrainClass.ManMade, "510", "line", "ЛЭП/канатка", "#6B7280", "zap", 90m, "Не влияет на бег"),
        new(TerrainClass.ManMade, "511", "line", "Магистральная ЛЭП", "#6B7280", "zap", 90m, "Не влияет на бег"),
        new(TerrainClass.ManMade, "512", "line", "Мост/туннель", "#111827", "bridge", 90m, "Обычно проходимо"),
        new(TerrainClass.ManMade, "513", "line", "Стена", "#111827", "wall", 20m, "Сильное замедление"),
        new(TerrainClass.ManMade, "514", "line", "Разрушенная стена", "#374151", "wall", 55m, "Частично проходима"),
        new(TerrainClass.ManMade, "515", "line", "Непреодолимая стена", "#111827", "wall", 0m, "Непреодолимо"),
        new(TerrainClass.ManMade, "516", "line", "Забор", "#111827", "fence", 45m, "Снижение скорости"),
        new(TerrainClass.ManMade, "517", "line", "Разрушенный забор", "#374151", "fence", 70m, "Частично проходим"),
        new(TerrainClass.ManMade, "518", "line", "Непреодолимый забор", "#111827", "fence", 0m, "Непреодолимо"),
        new(TerrainClass.ManMade, "519", "point", "Точка пересечения", "#111827", "waypoints", 100m, "Разрешенный переход"),
        new(TerrainClass.ManMade, "520", "area", "Запрещенная зона", "#111827", "ban", 0m, "Непреодолимо"),
        new(TerrainClass.ManMade, "521", "area", "Здание", "#111827", "building", 0m, "Непроходимо"),
        new(TerrainClass.ManMade, "522", "area", "Навес", "#374151", "warehouse", 85m, "Проходимо"),
        new(TerrainClass.ManMade, "523", "line", "Руины", "#374151", "building-2", 35m, "Сильное замедление"),
        new(TerrainClass.ManMade, "524", "point", "Высокая башня", "#111827", "tower-control", 75m, "Ориентир"),
        new(TerrainClass.ManMade, "525", "point", "Малая башня", "#111827", "tower-control", 78m, "Ориентир"),
        new(TerrainClass.ManMade, "526", "point", "Каменная пирамида/знак", "#111827", "landmark", 80m, "Ориентир"),
        new(TerrainClass.ManMade, "527", "point", "Кормушка", "#111827", "landmark", 80m, "Ориентир"),
        new(TerrainClass.ManMade, "528", "line", "Выраженный линейный объект", "#111827", "git-commit-horizontal", 75m, "Нужна легенда"),
        new(TerrainClass.ManMade, "529", "line", "Непреодолимый линейный объект", "#111827", "git-commit-horizontal", 0m, "Непреодолимо"),
        new(TerrainClass.ManMade, "530", "point", "Выраженный объект (кольцо)", "#111827", "circle", 80m, "Нужна легенда"),
        new(TerrainClass.ManMade, "531", "point", "Выраженный объект (крест)", "#111827", "plus", 80m, "Нужна легенда"),
        new(TerrainClass.ManMade, "532", "line", "Лестница", "#111827", "steps", 70m, "Проходимо с замедлением"),

        // Технические символы (ISOM 600).
        new(TerrainClass.TechnicalSymbols, "601", "line", "Линия магнитного севера", "#60A5FA", "compass", 100m, "Технический символ"),
        new(TerrainClass.TechnicalSymbols, "602", "point", "Регистрационная метка", "#60A5FA", "crosshair", 100m, "Технический символ"),
        new(TerrainClass.TechnicalSymbols, "603", "point", "Отметка высоты", "#8B5A2B", "ruler", 100m, "Технический символ"),

        // Обозначения дистанции (ISOM/ISSkiOM 700).
        new(TerrainClass.CourseMarkings, "701", "point", "Старт", "#A855F7", "play", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "702", "point", "Пункт выдачи карты", "#A855F7", "map-pin", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "703", "point", "Контрольный пункт", "#A855F7", "circle-dot", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "704", "text", "Номер/код КП", "#A855F7", "hash", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "705", "line", "Линия дистанции", "#A855F7", "route", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "706", "point", "Финиш", "#A855F7", "flag", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "707", "line", "Маркированный участок", "#A855F7", "route", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "708", "line", "Запретная граница", "#A855F7", "ban", 0m, "Нельзя пересекать"),
        new(TerrainClass.CourseMarkings, "709", "area", "Запретная зона дистанции", "#A855F7", "ban", 0m, "Нельзя пересекать"),
        new(TerrainClass.CourseMarkings, "710", "point", "Разрешенная точка пересечения", "#A855F7", "waypoints", 100m, "Символ дистанции"),
        new(TerrainClass.CourseMarkings, "711", "line", "Запретный маршрут", "#A855F7", "ban", 0m, "Нельзя использовать"),
        new(TerrainClass.CourseMarkings, "715", "point", "Продолжение после смены карты", "#A855F7", "forward", 100m, "ISSkiOM"),
        new(TerrainClass.CourseMarkings, "716", "line", "Запрещенный маршрут (не пересекать)", "#A855F7", "ban", 0m, "ISSkiOM"),
        new(TerrainClass.CourseMarkings, "717", "point", "Препятствие на лыжне", "#A855F7", "triangle-alert", 30m, "ISSkiOM"),
        new(TerrainClass.CourseMarkings, "720", "point", "Пункт смены снаряжения", "#A855F7", "backpack", 100m, "ISSkiOM"),

        // Обозначения лыжней (ISSkiOM 800).
        new(TerrainClass.SkiTrackMarkings, "801", "line", "Очень широкая лыжня > 3.0 м", "#16A34A", "route", 100m, "Максимально проходимо"),
        new(TerrainClass.SkiTrackMarkings, "802", "line", "Широкая лыжня 1.5-3.0 м", "#16A34A", "route", 96m, "Очень быстро"),
        new(TerrainClass.SkiTrackMarkings, "803", "line", "Лыжня 0.8-1.2 м", "#16A34A", "route", 92m, "Быстро"),
        new(TerrainClass.SkiTrackMarkings, "804", "line", "Медленная лыжня 0.8-1.0 м", "#16A34A", "route", 75m, "Умеренно"),
        new(TerrainClass.SkiTrackMarkings, "805", "line", "Дорога под снегом", "#111827", "route", 88m, "Обычно быстро"),
        new(TerrainClass.SkiTrackMarkings, "807", "line", "Нерасчищенная дорога", "#111827", "route", 40m, "Сильное замедление"),
        new(TerrainClass.SkiTrackMarkings, "808", "area", "Подготовленная лыжная зона", "#16A34A", "square", 95m, "Очень быстро"),
        new(TerrainClass.SkiTrackMarkings, "813", "line", "Публичный снегоходный маршрут", "#16A34A", "route", 65m, "Нестабильная проходимость"),
        new(TerrainClass.SkiTrackMarkings, "841", "point", "Одностороннее движение", "#16A34A", "arrow-right", 100m, "Организационный символ")
    ];
}
